version: '3'
services:
  crud_api:
    container_name: crud_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=admin;Password=123456"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "6543:5432"
    "volumes":
      - pgdata:/var/lib/postgresql/data
        
volumes:
  pgdata: {}